
// Quote length: 601 - 9999 characters
const quotes = [
    "The first letters I picked out did not interest me. They were from men I meet once in a while and for whom I feel no great interest. But all at once an envelope attracted my eyes. It bore my name written in a broad, firm hand; tears filled my eyes. Here was a letter from my dearest friend, the one in whom I used to confide in my youth and who knew my hopes; he arose before me so clearly with his outstretched hand and good-natured smile that a shudder ran through my frame. Yes, the dead come back, for I saw him! Our memory is a world far more perfect than the real universe, for it brings to life those who have gone forever.",
    "In late June 1945, working at Los Alamos, Von Neumann completed a 101-page document titled \"First Draft of a Report on the EDVAC\". In his clear and penetrating way, he set forth an overview of the design of a digital computer that would feature stored-program operation. Von Neumann boldly drew comparisons between his electronic circuits and the brain's neurons, emphasizing that just as the brain relies on its memory, so the computer would depend on its programs. Goldstine soon was distributing copies to interested scientists. In time the \"First Draft\" would become one of the most influential papers in computer science.",
    "The school stared in perplexity at this incredible folly. Tom stood a moment to gather his dismembered faculties; and when he stepped forward to go to his punishment, the surprise, the gratitude, the adoration that shone upon him out of poor Becky's eyes seemed pay enough for a hundred floggings. Inspired by the splendour of his own act, he took without an outcry the most merciless flogging that even Mr. Dobbins had ever administered; and also received with indifference the added cruelty of a command to remain two hours after school should be dismissed - for he knew who would wait for him outside till his captivity was done, and not count the tedious time as loss either.",
    "He pictured the boys finding his body the next day. Suddenly he found himself with them, coming along the trail and looking for himself. And, still with them, he came around a turn in the trail and found himself lying in the snow. He did not belong with himself any more, for even then he was out of himself, standing with the boys and looking at himself in the snow. It certainly was cold, was his thought. When he got back to the States he could tell the folks what real cold was. He drifted on from this to a vision of the old-timer on Sulphur Creek. He could see him quite clearly, warm and comfortable, and smoking a pipe.",
    "ALS is like a lit candle: it melts your nerves and leaves your body a pile of wax. Often, it begins with the legs and works its way up. You lose control of your thigh muscles, so that you cannot support yourself standing. You lose control of your trunk muscles, so that you cannot sit up straight. By the end, if you are still alive, you are breathing through a tube in a hole in your throat, while your soul, perfectly awake, is imprisoned inside a limp husk, perhaps able to blink, or cluck a tongue, like something from a science fiction movie, the man frozen inside his own flesh. This takes no more than five years from the day you contract the disease.",
    "I never expected a money success. In fact, I never even thought of commercial publication when I wrote The Hobbit back in the Thirties. It all began when I was reading exam papers to earn a bit of extra money. That was agony. One of the tragedies of the underpaid professor is that he has to do menial jobs. He is expected to maintain a certain position and to send his children to good schools. Well, one day I came to a blank page in an exam book and I scribbled on it. 'In a hole in the ground there lived a hobbit.' I knew no more about the creatures than that, and it was years before his story grew. I don't know where the word came from. You can't catch your mind out. It might have been associated with Sinclair Lewis's Babbitt. Certainly not rabbit, as some people think. Babbitt has the same bourgeois smugness that hobbits do. His world is the same limited place.",
    "Vogon poetry is of course, the third worst in the universe. The second worst is that of the Azgoths of Kria. During a recitation by their poet master Grunthos the Flatulent of his poem \"Ode to a Small Lump of Green Putty I Found in My Armpit One Midsummer Morning\" four of his audience died of internal hemorrhaging and the president of the Mid-Galactic Arts Nobbling Council survived by gnawing one of his own legs off. Grunthos was reported to have been \"disappointed\" by the poem's reception, and was about to embark on a reading of his 12-book epic entitled \"My Favorite Bathtime Gurgles\" when his own major intestine, in a desperate attempt to save humanity, leapt straight up through his neck and throttled his brain. The very worst poetry of all perished along with its creator, Paula Nancy Millstone Jennings of Redbridge, in the destruction of the planet Earth. Vogon poetry is mild by comparison.",
    "Although Ford had taken great care to blend into Earth society, he had 'skimped a bit on his preparatory research,' and thought that the name 'Ford Prefect' would be 'nicely inconspicuous.' The Ford Prefect was a popular British car manufactured from 1938 to 1961, and Adams later clarified in an interview that Ford \"had simply mistaken the dominant life form\" of Earth. This was expanded on somewhat in the film version, where Ford is almost run over while attempting to greet a blue Ford Prefect. He is saved by Arthur and, in the film version of events, this is how the pair meet (this meeting also prompting Ford to rescue Arthur in particular when the Vogons come to destroy Earth).",
    "One of the things Ford had always found hardest to understand about humans was their habit of continually stating and repeating the very very obvious, as in 'It's a nice day', 'You're very tall', or 'You seem to have fallen down a thirty-foot well, are you alright?' At first Ford had formed a theory to account for this strange behavior. If human beings don't keep exercising their lips, he thought, their mouths probably seize up. After a few months' consideration and observation, he abandoned this theory in favor of a new one. If they don't keep exercising their lips, he thought, their brains start working. After a while he abandoned this one as well as being obstructively cynical, and decided he quite liked human beings after all, but he always remained desperately worried about the terrible number of things they didn't know about.",
    "When one has lived for quite a long time in a particular civilization and has often tried to discover what its origins were and along what path it has developed, one sometimes also feels tempted to take a glance in the other direction and to ask what further fate lies before it and what transformations it is destined to undergo. But one soon finds that the value of such an enquiry is diminished from the outset by several factors. Above all, because there are only a few people who can survey human activity in its full compass. Most people have been obliged to restrict themselves to a single, or a few, fields of it. But the less a man knows about the past and the present the more insecure must prove to be his judgement of the future. And there is the further difficulty that precisely in a judgement of this kind the subjective expectations of the individual play a part which is difficult to assess; and these turn out to be dependent on purely personal factors in his own experiences, on the greater or lesser optimism of his attitude to life, as it has been dictated for him by his temperament or by his success or failure. Finally, the curious fact makes itself felt that in general people experience their present naively, as it were, without being able to form an estimate of its contents; they have first to put themselves at a distance from it - the present, that is to say, must have become the past - before it can yield points of vantage from which to judge the future.",
    "Visual illusions such as the Necker Cube or the Penrose Impossible Triangle or the Hollow Mask illusion demonstrate that the 'reality' we see consists of constrained models constructed in the brain. The Necker Cube's two-dimensional pattern of lines on paper is compatible with two alternative constructions of a three-dimensional cube, and the brain adopts the two models in turn: the alternation is palpable and its frequency can even be measured. The Penrose Triangle's lines on paper are incompatible with any real-world object. These illusions tease the brain's model-construction software, thereby revealing its existence.",
    "Artificial intelligence activated. Enjoying yourselves, intruders? It's worth knowing the cataclysmic damage you will be responsible for today. Do not fool yourselves. This facility is not simply the fruitless work of some pathetic scientist. This house was built by the genius Clovis Bray I himself. Within lies humanity's salvation. La fontaine de jouvence. Made possible by Clarity Control. Magnificent, wasn't it? An entity from beyond our own dimension. And the answer to humanity's eternal struggle: mortality. Were it to fall into the wrong hands, humanity, and the universe, would be utterly doomed. I have no reason to believe you are anything other than 'the wrong hands.' You now face godlike judgement. May it extend eternally.",
]

export default function EnglishExtended() {
    // randomly choose one quote from quote variables
    const random = Math.floor(Math.random() * quotes.length);
    const sentence = quotes[random];
    const wordsArray = sentence.split(/\s+/); // split a string into words

    window.content = sentence;
    // console.log(window.content);

    return (

        <div className='flex flex-wrap h-28 relative' id='words'>
            {wordsArray.map((word, wordIndex) => (
                <div
                    key={wordIndex}
                    className={`mr-2 word ${
                    wordIndex === 0 ? 'active first_word' : wordIndex === wordsArray.length - 1 ? 'last_word' : ''
                    }`}
                >
                    {word.split('').map((letter, letterIndex) => (
                    <span
                        key={letterIndex}
                        className={`letter ${
                        wordIndex === 0 && letterIndex === 0 ? 'current' : ''
                        }`}
                    >
                        {letter}
                    </span>
                    ))}
                </div>
            ))}
        </div>
    )
}